name: Create Pull Request to Develop

on:
  pull_request:
    branches: [ "develop" ]
    types: ["opened","synchronize","reopened"]
    #

jobs:
  Unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Unit Test
        run: mvn test

